name: Build Docker Container & Publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  release:
    types: [created]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t joanferrecid098/discord-dynip:latest
          docker build . -t joanferrecid098/discord-dynip:${{ github.event.release.tag_name }}
      - name: publish
        run: |
          docker login -u joanferrecid098 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push joanferrecid098/discord-dynip:latest
          docker push joanferrecid098/discord-dynip:${{ github.event.release.tag_name }}