# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup and run the project
      run: npm ci
    - run: npm start
    - name: Change the stored IP
      run: cp src/ip-adr.json src/saved-ip-adr.json
    - run: echo '{"ip":"1.1.1.1"}' > src/ip-adr.json
    - run: npm start
    - name: Check that the IP has changed
      uses: LouisBrunner/diff-action@v2.0.0
      with:
        old: src/ip-adr.json
        new: src/saved-ip-adr.json
        mode: strict
        tolerance: same
        output: difference.txt